# This is a basic workflow to help you get started with Actions

name: Release-Win-x64

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  release:
    types: [ published ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Publish
        run: dotnet publish -c Release -r win-x64
      - name: Pack files
        run: |
          cd bin/Release/net5.0/win-x64/
          tar -zcvf Cai1Hsu-BlackShark2Driver.tar.gz ./publish
          $release_file_path="$(pwd)\Cai1Hsu-BlackShark2Driver.tar.gz"
          echo $release_file_path
          chcp 65001
          echo "release_file_path=$release_file_path" >> $env:GITHUB_ENV
          echo "pack ended."
      - name: Deploy
        uses: WebFreak001/upload-asset@v1.0.0
        with:
          file: ${{ env.release_file_path }}
          name: 'Cai1Hsu-BlackShark2Driver.tar.gz'
          mime: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
